### ISSUE TITLE
大佬这个好像有点问题

### ISSUE THREAD

**Issue by qwert123123123** [guyuehome/multirobot_formation#1]
下载到工作空间之后，编译会有错误。错误提示：
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "move_base_msgs"
  with any of the following names:

    move_base_msgsConfig.cmake
    move_base_msgs-config.cmake

  Add the installation prefix of "move_base_msgs" to CMAKE_PREFIX_PATH or set
  "move_base_msgs_DIR" to a directory containing one of the above files.  If
  "move_base_msgs" provides a separate development package or SDK, be sure it
  has been installed.
thanks

**Comment by huchunxu** [comment]
缺包，按照错误提示安装：
sudo apt-get install ros-kinetic-move-base-msgs



huchunxu@ps-micro.com
 
发件人： qwert123123123
发送时间： 2020-06-29 16:49
收件人： guyuehome/multirobot_formation
抄送： Subscribed
主题： [guyuehome/multirobot_formation] 大佬这个好像有点问题 (#1)
下载到工作空间之后，编译会有错误。错误提示：
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
Could not find a package configuration file provided by "move_base_msgs"
with any of the following names:
move_base_msgsConfig.cmake
move_base_msgs-config.cmake

Add the installation prefix of "move_base_msgs" to CMAKE_PREFIX_PATH or set
"move_base_msgs_DIR" to a directory containing one of the above files. If
"move_base_msgs" provides a separate development package or SDK, be sure it
has been installed.
thanks
―

**Comment by qwert123123123** [comment]
> 缺包，按照错误提示安装： sudo apt-get install ros-kinetic-move-base-msgs huchunxu@ps-micro.com 发件人： qwert123123123 发送时间： 2020-06-29 16:49 收件人： guyuehome/multirobot_formation 抄送： Subscribed 主题： [guyuehome/multirobot_formation] 大佬这个好像有点问题 (#1) 下载到工作空间之后，编译会有错误。错误提示： CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package): Could not find a package configuration file provided by "move_base_msgs" with any of the following names: move_base_msgsConfig.cmake move_base_msgs-config.cmake Add the installation prefix of "move_base_msgs" to CMAKE_PREFIX_PATH or set "move_base_msgs_DIR" to a directory containing one of the above files. If "move_base_msgs" provides a separate development package or SDK, be sure it has been installed. thanks ― You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢大佬
